server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://192.168.252.128:5433/interview_ai
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  upload:
    path: D:/JavaProject/AiProject/uploads
  ai:
    base-url: https://api-inference.modelscope.cn/v1
    api-key: ms-bd09c5d5-032a-4801-9409-02dde7089f9b
    model: Qwen/Qwen3.5-27B